name: spleef
version: '1.0-SNAPSHOT'
main: me.dylano.spleef.Spleef
api-version: '1.20'
commands:
  startspleef:
    description: Start een Spleef-wedstrijd.
  joinspleef:
    description: Join een Spleef-wedstrijd.
  gamemode:
    description: Verander je game mode. Gebruik /gamemode survival of /gamemode creative.
